# =========================================================================
# Title: kickstarter_randomforest.R
# Author: Matt Buckley
# Description: Classification by randomForest using data generated by
# web_scraper_thekickbackmachine.R
# Liscense: MIT license: http://www.opensource.org/licenses/mit-license.php 
# =========================================================================

## STEPS
# 1. load data generated by web_scraper_thekickbackmachine.R
# 2. subset data
# 3. run randomForest
# 4. plot variable importance
# 5. plot error vs. number of trees

load('kickscrape_df.Rda')

library(randomForest)

# subset kickscrape.df
data<-data.frame(kickscrape.df$success,kickscrape.df$category,kickscrape.df$goal)
names(data)<-c('success', 'category', 'goal')

n <- nrow(data)
val.size <- round(n/4)
s <- sample(n,val.size,replace=F)
data.train <- data[-s,]
data.test <- data[s,]
train.x <- data.frame(data.train[,2:3]) 
train.y <- data.frame(data.train[,1])
test.x<- data.frame(data.test[,2:3]) 
test.y <- data.frame(data.test[,1])

# run randomForest
rf_model<-randomForest(success~.,data=data.train,
                       xtest=test.x, ytest=test.y,importance=TRUE,proximity=TRUE)
#print results
print(rf_model)

#plot variable importance
varImpPlot(rf_model, main='Random Forest: Variable Importance')

# plot error vs. number of trees
plot(rf_model, main='Random Forest: Number of Trees vs Error')
