# =========================================================================
# Title: kickstarter_bubbleplot.R
# Author: Matt Buckley
# Description: Bubble plot of kickstarter data generated by 
# web_scraper_thekickbackmachine.R
# Liscense: MIT license: http://www.opensource.org/licenses/mit-license.php 
# =========================================================================

load('kickscrape_df.Rda')

successes.df <- subset(kickscrape.df, success==1)
failures.df <- subset(kickscrape.df, success==0)
success.counts <- data.frame(table(successes.df$category))
failure.counts <- data.frame(table(failures.df$category))
kickscrape_plots.df <- data.frame(successes=success.counts$Freq,failures=failure.counts$Freq)
row.names(kickscrape_plots.df) <- success.counts$Var1


library(colortools)


s<-data.frame(kickscrape_plots.df$successes, row.names=rownames(kickscrape_plots.df))
f<-data.frame(kickscrape_plots.df$failures, row.names=rownames(kickscrape_plots.df))
# specify colors 
n = 13
col_names = hcl(h=seq(13, 375-360/n, length=n)%%360, c=100, l=65)
# set graphic margins
op = par(mar = c(4, 3, 4, 1))
# call new plot
plot.new()
# define plot window
plot.window(xlim = c(0, 780),
            ylim = c(50, 2500))
# add axis
axis(side=1, pos=0, col="gray50", cex.axis=1)
axis(side=2, pos=0, las=2,
     col="gray50", cex.axis=1)
# add y-axis legend
mtext("Number of Failures", side=1, line=2)
mtext("Number of Successes", side=2, line=1.5)
# add legend
legend(40, 2500, legend=rownames(kickscrape_plots.df)[1:n], col=col_names, pt.cex=1, 
       pch=20, bty="n", cex=0.8, text.col="gray30")
# add data
for (i in 1:n)
{
  # define colors
  cols = sequential(col_names[i], plot=FALSE)
  # add points
  size = as.numeric(log(f[i,] / 10))
  points(f[i,], s[i,], pch=20, col=cols[i], cex=8)
}
# add title
mtext("Successes vs. Failures", side=3, at=400, line=1.5, col="gray20", cex=1.5, font=2)
mtext("by project category", side=3, at=400, line=-0.1, cex=1, col="gray30")
# turn off par
par(op)